
// deno-fmt-ignore-file
// deno-lint-ignore-file no-explicit-any ban-types ban-unused-ignore
//
// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// To generate this file: deno task start
//        


export interface OpenAPI {
/**
 * Registers a new storefront user in VTEX ID using a unique login key (username) as `identifier`.
 * 
 *  The created user is not linked to any Organization Unit and does not have storefront permissions.
 * 
 * Once a storefront user is added, it cannot be edited or removed. If incorrect data is uploaded, create a new username.
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | VTEX ID | User Management | **Create User** |
 * 
 * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint.
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 * 
 * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
 */
"POST /api/authenticator/storefront/users": {
searchParams: {
/**
 * Defines whether the storefront user should recover their password via an external service (`true`) or define a new password on first login (`false`, default).
 */
isLegacyPassword?: boolean
}
body: {
/**
 * Unique login key (username) for the user. Case-insensitive string (3-70 characters, accepts special characters and whitespace) used for login.
 */
identifier: string
/**
 * Type of identifier. Only `username` is supported.
 */
identifierType: "username"
}
response: {
/**
 * Unique user identifier (GUID).
 */
userId?: string
}
}
/**
 * Fetches a storefront user by their identifier (username or email). The identifier must be provided as a URL-encoded query parameter.
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | VTEX ID | User Management | **View User** |
 * 
 * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint.
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 * 
 * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
 */
"GET /api/vtexid/pvt/user/info": {
searchParams: {
/**
 * URL-encoded storefront user identifier (username or email).
 */
user: string
}
/**
 * Storefront user information.
 */
response: {
/**
 * Storefront user unique identifier.
 */
userId?: string
/**
 * Storefront user email.
 */
user?: string
/**
 * Storefront user full name.
 */
name?: string
/**
 * VTEX account ID.
 */
accountId?: string
/**
 * VTEX VTEX account name.
 */
accountName?: string
}
}
/**
 * Generate a [token](https://developers.vtex.com/vtex-rest-api/docs/getting-started-authentication#user-token) from a given [app key and app token](https://help.vtex.com/en/tutorial/api-keys--2iffYzlvvz4BDMr6WGUtet) pair. You can use this token to authenticate requests to VTEX APIs by sending it as a header named `VtexIdclientAutCookie`. The token's permissions are the same as [defined to the credential pair](https://help.vtex.com/en/tutorial/api-keys--2iffYzlvvz4BDMr6WGUtet#managing-app-key-permissions).
 * 
 * > Since you are sending the credentials on the request body, there is no need to send authentication headers. 
 * 
 * > It is also possible to make this request using the `https://api.vtexcommercestable.com.br/api/vtexid/apptoken/login?an={accountName}` route, replacing `{accountName}` with your VTEX account name. This is the only case where you need to use the `an` query parameter.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/apptoken/login": {
searchParams: {
/**
 * Name of your VTEX account.
 */
an?: string
}
/**
 * Credentials object, composed of API key and application token.
 */
body: {
/**
 * API key.
 */
appkey: string
/**
 * Application token corresponding to the API key sent with it.
 */
apptoken: string
}
response: {
/**
 * Authentication status.
 */
authStatus?: string
/**
 * Authentication token.
 */
token?: string
/**
 * Token expiration Unix timestamp in seconds.
 */
expires?: number
}
}
/**
 * If your store uses a headless frontend, you can authenticate users via OAuth and use this endpoint to exchange the OAuth access token for a VTEX authentication token. This VTEX token can be used to authenticate your frontend requests to VTEX APIs.
 * 
 * Learn more about how to implement [headless authentication](https://developers.vtex.com/docs/guides/headless-authentication) in your store.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/audience/webstore/provider/oauth/exchange": {
body: {
/**
 * Name of the [OAuth provider](https://developers.vtex.com/docs/guides/login-integration-guide-webstore-oauth2) set up in your Admin panel.
 */
providerId: string
/**
 * Access token obtained from your frontend via OAuth integration corresponding with the indicated `providerId`.
 */
accessToken: string
/**
 * Duration of the token that will be returned, in minutes. The maximum value is `120`. The default is `60` when the duration isn't defined.
 */
duration?: number
}
response: {
/**
 * Authentication token. Use this token to authenticate your requests to VTEX APIs.
 */
authToken?: string
}
}
/**
 * Retrieves information about the user who is currently authenticated in your store, given an user token. If the user is not authenticated, the response for this API will be `401 (Unauthorized)`.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/credential/validate": {
searchParams: {
/**
 * Name of your VTEX account.
 */
an?: string
}
/**
 * Request body object.
 */
body: {
/**
 * Value of the `VtexIdclientAutCookie`, [user token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.
 */
token: string
}
response: {
/**
 * Authentication status.
 */
authStatus?: string
/**
 * Unique identifier of the user within VTEX services.
 */
id?: string
/**
 * User email.
 */
user?: string
/**
 * VTEX account name.
 */
account?: string
/**
 * Type of user.
 */
audience?: string
/**
 * Type of token.
 */
tokenType?: string
}
}
/**
 * Defines if user passwords can be repeated in your store. 
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | VTEX ID | Identity Providers | **Write Identity Providers** |
 * 
 * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint.
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 * 
 * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
 */
"POST /api/vtexid/pub/providers/setup/password/webstore/password": {
body: {
/**
 * Defines if password access is active (`true`) or not (`false`).
 */
isActive?: boolean
/**
 * Defines if passwords can be repeated (`true`) or not (`false`).
 */
allowRepeated?: boolean
}
}
/**
 * Expires an user's password in your store.
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | VTEX ID | User Management | **Expire User Password** |
 * 
 * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint.
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 * 
 * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
 */
"POST /api/vtexid/password/expire": {
searchParams: {
/**
 * User email.
 */
email: string
}
}
/**
 * Starts the API token renewal process by generating a new token while keeping the current token active. This ensures a smooth transition without service disruption.
 * 
 * The previous token and the new token are both valid until the renewal process is completed by making a request to `PATCH` [Complete token renewal](https://developers.vtex.com/docs/api-reference/vtex-id-api#patch-/api/vtexid/apikey/-apiKey-/apitoken/finish-renewal).
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | License Manager | API Key Management | **Renew API Token** |
 * 
 * You can [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) with that resource or use one of the following [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy):
 * 
 * | **Role** | **Resource** |
 * | --------------- | ----------------- |
 * | User Administrator - RESTRICTED | **Renew API Token** |
 * 
 * >❗ Assigning a [predefined role](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) to users or application keys usually grants permission to multiple [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see [Best practices for using application keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm).
 * 
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 */
"PATCH /api/vtexid/apikey/:apiKey/apitoken/renew": {
response: {
/**
 * Unique identifier of the API token.
 */
id?: string
/**
 * Name assigned to the API key.
 */
keyName?: string
/**
 * ISO 8601 timestamp indicating when the current token was created.
 */
creationDateToken?: string
/**
 * ISO 8601 timestamp indicating when the new token was generated.
 */
creationDateNewToken?: string
/**
 * Number of days the token remains valid before expiration.
 */
expirationPeriod?: number
/**
 * New API token value.
 */
newToken?: string
}
}
/**
 * Finalizes the API token renewal process, deactivating the old token. After this step, the old token can no longer be used, ensuring security by enforcing a controlled rotation.
 * 
 * ## Permissions
 * 
 * Any user or [API key](https://developers.vtex.com/docs/guides/authentication-overview#api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
 * 
 * | **Product** | **Category** | **Resource** |
 * | --------------- | ----------------- | ----------------- |
 * | License Manager | API Key Management | **Renew API Token** |
 * 
 *  You can [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) with that resource or use one of the following [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy):
 * 
 * | **Role** | **Resource** |
 * | --------------- | ----------------- |
 * | User Administrator - RESTRICTED | **Renew API Token** |
 * 
 * >❗ Assigning a [predefined role](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) to users or application keys usually grants permission to multiple [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see [Best practices for using application keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm).
 * 
 * To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#machine-authentication).
 */
"PATCH /api/vtexid/apikey/:apiKey/apitoken/finish-renewal": {
response: {
/**
 * Unique identifier of the API token.
 */
id?: string
/**
 * ISO 8601 timestamp indicating when the current token was created.
 */
creationDateToken?: string
/**
 * Creation date of the new token. Always `null` after the token creation process is completed.
 */
creationDateNewToken?: (null | string)
}
}
/**
 * Retrieves the unique user ID for a given email address.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). However, it does require a valid user token (`VtexIdclientAutCookie`) to be included in the request headers.
 * 
 * To learn more about user authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication-overview#user-authentication).
 */
"GET /api/vtexid/pvt/user/id": {
searchParams: {
/**
 * URI-encoded user email.
 */
usuario: string
}
/**
 * User ID.
 */
response: (null | string)
}
/**
 * Starts the authentication flow for a user in your store. This endpoint returns an authentication token valid for 24 hours.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"GET /api/vtexid/pub/authentication/start": {
searchParams: {
/**
 * Account name.
 */
scope: string
/**
 * Optional device fingerprint for enhanced security. Generated client-side using JavaScript libraries that collect anonymized device and browser parameters to create a unique identifier. When submitted in this request, it must later be provided when making a request to [refresh token](https://developers.vtex.com/docs/api-reference/vtex-id-api#post-/api/vtexid/refreshtoken/webstore).
 */
fingerprint?: string
}
response: {
/**
 * Authentication token provided to the user, valid for 24 hours.
 */
authenticationToken?: string
/**
 * List of available OAuth providers.
 */
oauthProviders?: {
/**
 * Name of the OAuth provider.
 */
providerName?: string
/**
 * Class name associated with the provider.
 */
className?: string
/**
 * Additional context expected by the provider.
 */
expectedContext?: string[]
}[]
/**
 * Indicates whether classic authentication is enabled (`true`) or not (`false`).
 */
showClassicAuthentication?: boolean
/**
 * Indicates whether access key authentication is enabled (`true`) or not (`false`).
 */
showAccessKeyAuthentication?: boolean
/**
 * Indicates whether passkey authentication is enabled (`true`) or not (`false`).
 */
showPasskeyAuthentication?: boolean
/**
 * Authentication cookie if available.
 */
authCookie?: (null | string)
/**
 * Indicates whether the user is authenticated.
 */
isAuthenticated?: boolean
/**
 * Currently selected authentication provider, if any.
 */
selectedProvider?: (null | string)
/**
 * List of available SAML providers.
 */
samlProviders?: string[]
}
}
/**
 * Sends an access key to the user's email address, if the response is empty with 200 OK. The access key is used to authenticate the user in your store.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/pub/authentication/accesskey/send": {
searchParams: {
/**
 * User email.
 */
email: string
}
}
/**
 * Validates the user session using the access key sent to the user through the [Send access key](https://developers.vtex.com/docs/api-reference/vtex-id-api#post-/api/vtexid/pub/authentication/accesskey/send) endpoint.
 * 
 * The refresh token (`vid_rt`) is returned in the `Set-Cookie` header. This token is required for the [Refresh token](https://developers.vtex.com/docs/api-reference/vtex-id-api#post-/api/vtexid/refreshtoken/webstore) request.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/pub/authentication/accesskey/validate": {
/**
 * Validate session response object.
 */
response: {
/**
 * Authentication status of the user, which can be: 
 * 
 * * `Success`: when authentication is completed successfully.
 * * `InvalidEmail`: When the email informed is not valid.
 * * `InvalidToken`: When the token is malformed, expired, or has an invalid signature.
 * * `WrongCredentials`: When the informed credentials are not valid.
 */
authStatus?: ("Success" | "InvalidEmail" | "InvalidToken" | "WrongCredentials")
/**
 * Indicates whether multi-factor authentication is required.
 */
promptMFA?: boolean
/**
 * Last authentication attempt available.
 */
lastAttemptAvailable?: (null | number)
/**
 * Client token.
 */
clientToken?: (null | string)
/**
 * Authentication cookie.
 */
authCookie?: (null | {
/**
 * Name of the cookie.
 */
Name?: string
/**
 * Value of the cookie.
 */
Value?: string
})
/**
 * Cookie specific to account authentication.
 */
accountAuthCookie?: (null | {
/**
 * Name of the cookie.
 */
Name?: string
/**
 * Value of the cookie.
 */
Value?: string
})
/**
 * Time in seconds until authentication expires.
 */
expiresIn?: number
/**
 * Unique identifier for the authenticated user.
 */
userId?: (null | string)
/**
 * User's phone number associated with the account.
 */
phoneNumber?: (null | string)
/**
 * Authentication scope granted.
 */
scope?: (null | string)
}
}
/**
 * Returns a valid refresh token and authentication token (`VtexIdclientAutCookie`) as cookies.
 * 
 * ## Permissions
 * 
 * This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
 */
"POST /api/vtexid/refreshtoken/webstore": {
body: {
/**
 * Optional device fingerprint for enhanced security. Generated client-side using JavaScript libraries that collect anonymized device and browser parameters to create a unique identifier. Must remain consistent with the fingerprint provided during [initial authentication](https://developers.vtex.com/docs/api-reference/vtex-id-api#get-/api/vtexid/pub/authentication/start), if previously submitted.
 */
fingerprint?: (null | string)
}
/**
 * Refresh token response object.
 */
response: {
/**
 * Status of the operation. Possible values: 
 * - `Success`: Token refresh was successful. 
 * - `InvalidSession`: The session is invalid or expired. 
 * - `InvalidToken`: The token is invalid. 
 * - `InvalidEmail`: The email associated with the token is invalid. 
 * - `InvalidScope`: The scope is invalid.
 */
status?: ("Success" | "InvalidSession" | "InvalidToken" | "InvalidEmail" | "InvalidScope")
/**
 * Unique identifier assigned to the authenticated user.
 */
userId?: string
/**
 * The timestamp indicating when the session should be refreshed, in ISO 8601 format (`YYYY-MM-DDTHH:mm:ss±HH:MM`).
 */
refreshAfter?: string
}
}
}
